### ISSUE TITLE
Only getting 422 as response

### ISSUE THREAD

**Issue by garyee** [aminariana/data-uri-to-img-url#2]
Hi,

I've tried to call "http://data-uri-to-img-url.herokuapp.com/images.json" with all the parameter constallations imaginable.
But I only got the 422 html error response to my ajax call.
```
var imageData = $('canvas').toDataURL("image/png");
 var imageDataRaw = imageData.replace(/^data:image\/\w+;base64,/, "");
$.ajax({
            url:"http://data-uri-to-img-url.herokuapp.com/images.json",
            type:"POST",
            data:{'image':{'data_uri':imageDataRaw}},
            success:function(data){
                console.log(data);
            },
            error:function(shr,status,data){
                console.log("error " + data + " Status " + shr.status);
            },
        });`

What I am doing wrong?

**Comment by aminariana** [comment]
Hi @garyee , I created a working example, `example.js.html`, from your script. The issue was that the server was not allowing cross-domain requests, which I have now allowed (CORS Headers)

https://github.com/aminariana/data-uri-to-img-url/blob/master/example.js.html

Screenshot of working example:

![screen shot 2016-12-12 at 12 11 16 pm](https://cloud.githubusercontent.com/assets/1071917/21115018/3af42bca-c064-11e6-9445-51beceb03ce1.png)

Thanks!

**Comment by garyee** [comment]
Tanks man!!!
